const { SlashCommandBuilder } = require('@discordjs/builders');
const wait = require('util').promisify(setTimeout);

module.exports = {

    data: new SlashCommandBuilder()
        .setName('advice')
        .setDescription('Frage nach einem Ratschlag!')
        .addStringOption(option =>
            option.setName('frage')
                .setDescription('Deine Frage für die du einen Rat brauchst.')
                .setRequired(false)),

    /**
     * @param {import('discord.js').Interaction} interaction
     */
    async execute(interaction) {
        await interaction.deferReply();
        const Discord = require('discord.js');
        const frage = interaction.options.getString('frage');
        let antwortenQuestion = [
            'Ja.',
            'Ja.',
            'Ja.',
            'Ja.',
            'Ja.',
            'Ja.',
            'Ja.',
            'Ja.',
            'Ja.',
            'Ja.',
            'Nein',
            'Nein',
            'Nein',
            'Nein',
            'Nein',
            'Nein',
            'Nein',
            'Nein',
            'Nein',
            'Nein',
            'Schmeiß dich bitte von der Brücke.',
            'Rede mit einem Freund darüber.',
            'Trink erstmal ne Tasse Tee.',
            'Leg dich mit den Mods darüber an.',
            'Gib den Franzosen die Schuld.',
            'Was du heute kannst besorgen, das verschiebe nicht auf morgen.',
            'Was du heute kannst besorgen, das verschiebste ganz entspannt auf morgen.',
            'Bro, ich bin nur ein Bot... Woher soll ich das wissen??',
            'Wambologie.',
            'Ich liebe sie.',
            'Genieße den Moment.',
            'Sei freundlich zu dir selbst.',
            'Lächle öfter.',
            'Probier mal etwas Neues aus.',
            'Hör auf dein Bauchgefühl.',
            'Nimm dir Zeit für Selbstreflexion.',
            'Setze klare Ziele für dich.',
            'Bleib positiv, auch wenn es schwer ist.',
            'Sei offen für Veränderungen.',
            'Sei dankbar für die kleinen Dinge.',
            'Sag öfter mal "Nein", wenn es notwendig ist.',
            'Finde einen Weg, Stress abzubauen.',
            'Schätze die Vielfalt in deinem Leben.',
            'Akzeptiere, dass Perfektion nicht existiert.',
            'Teile deine Gedanken mit anderen.',
            'Nimm dir Zeit für Ruhepausen.',
            'Investiere in deine persönliche Entwicklung.',
            'Vertraue auf den Prozess des Lebens.',
            'Schätze die Bedeutung von Freundschaft.',
            'Finde Freude in den kleinen Momenten.',
            'Habe Geduld mit dir selbst.',
            'Manchmal ist es okay, nicht alles zu verstehen.',
            'Liebe dich selbst, bevor du jemand anderen liebst.',
            'Ja, aber nur wenn du eine Banane auf dem Kopf balancierst.',
            'Nein, es sei denn, du möchtest eine Karriere als professioneller Luftgitarrenspieler beginnen.',
            'Ja, aber nur wenn du vorher drei Mal im Kreis hüpfst.',
            'Nein, es sei denn, du kannst gleichzeitig rückwärts singen und rülpsen.',
            'Ja, aber nur wenn du dir vorstellst, dass du ein Einhorn auf Rollschuhen bist.',
            'Nein, es sei denn, du kannst einen Handstand machen und dabei Shakespeare rezitieren.',
            'Ja, aber nur wenn du eine Hula-Hoop-Performance für deine Zimmerpflanzen gibst.',
            'Nein, es sei denn, du trägst Socken auf den Händen und Handschuhe an den Füßen.',
            'Ja, aber nur wenn du es im Stile eines Pinguins machst.',
            'Nein, es sei denn, du kannst den Mond in einem Teelöffel balancieren.',
            'Ja, aber nur wenn du dabei singst: "Ich bin ein Toastbrot, hör mich knuspern."',
            'Nein, es sei denn, du trägst einen Bowler-Hut und sprichst mit einem britischen Akzent.',
            'Ja, aber nur wenn du einen Regenbogen durch deine Nase pusten kannst.',
            'Nein, es sei denn, du tanzt Walzer mit deinem Staubsauger, während du Kekse jonglierst.',
            'Ja, aber nur wenn du deinen Schatten als persönlichen Coach mitnimmst.',
            'Nein, es sei denn, du kannst einen Gummihuhn-Chor dirigieren.',
            'Ja, aber nur wenn du dabei in einer imaginären Seifenblase schwebst.',
            'Nein, es sei denn, du kannst eine Pizza mit den Füßen jonglieren.',
            'Ja, aber nur wenn du eine Melodie für deine Kaffeetasse komponierst.',
            'Nein, es sei denn, du kannst rückwärts rülpsen und dabei das Alphabet aufsagen.',
            'Ja, aber nur wenn du es rückwärts machst, während du auf einem Bein hüpfst.',
            'Nein, es sei denn, du kannst dabei das Alphabet rückwärts aufsagen und Gummibärchen jonglieren.',
            'Ja, aber nur wenn du es in einem Einhorn-Kostüm tust.',
            'Nein, es sei denn, du hast zuvor eine Ode an deine Zahnseide verfasst.',
            'Ja, aber nur wenn du es mit einem Lächeln auf dem Gesicht machst, während du rückwärts läufst.',
            'Nein, es sei denn, du kannst das Geräusch eines Pinguins imitieren und dabei Limbo tanzen.',
            'Ja, aber nur wenn du vorher eine Tasse Tee für deine Zimmerpflanzen zubereitest.',
            'Nein, es sei denn, du kannst dabei eine Shakespeare-Sonett rezitieren.',
            'Ja, aber nur wenn du es machst, während du auf einem imaginären Surfbrett stehst.',
            'Nein, es sei denn, du kannst dabei eine originelle Ballade über deine Socken singen.',
            'Ja, aber nur wenn du es mit einem Zirkuszelt als Umgebung machst.',
            'Nein, es sei denn, du trägst dabei einen Helm aus Wassermelone.',
            'Ja, aber nur wenn du es in Zeitlupe machst und dabei eine Geschichte über den Mond erzählst.',
            'Nein, es sei denn, du hast vorher einen Vertrag mit den Ameisen in deinem Garten unterzeichnet.',
            'Ja, aber nur wenn du es auf einem Trampolin machst, während du einen Regenschirm hältst.',
            'Nein, es sei denn, du kannst dabei einen Handstand auf einem Paddelbrett machen.',
            'Ja, aber nur wenn du es mit einem Lächeln und einem Löffel voll Glitzer machst.',
            'Nein, es sei denn, du trägst dabei einen Superheldenumhang und singst "Ich bin ein Toastbrot".',
            'Ja, aber nur wenn du es als Hommage an die unsichtbaren Gummihühner machst.',
            'Nein, es sei denn, du kannst dabei einen Tango mit einem Schatten tanzen.',
            'Mach es und füge Glitzer hinzu!',
            'Vermeide es, es könnte zu Konfetti-Regen führen.',
            'Natürlich, und vergiss nicht zu lächeln!',
            'Lass es lieber, es könnte die Schwerkraft herausfordern.',
            'Sing eine Hymne für Gummienten dabei.',
            'Besser nicht, das Universum mag seine Balance.',
            'Ja, und bring Tee für die Zimmerpflanzen mit.',
            'Versuche Stand-up-Comedy mit Zahnseide stattdessen.',
            'Tanze auf dem Regenbogen und sing eine Socken-Ode.',
            'Besser nicht, es könnte das Gedicht des Mondes stören.',
            'Warum nicht, mach es wie ein Abenteurer!',
            'Trag den Schokoladenhelm und mach eine Ballade über den Mond.',
            'Sing eine Ballade und tanze im Regen.',
            'Verhandle nicht mit Ameisen, das könnte chaotisch werden.',
            'Spring auf dem Trampolin mit Marshmallow-Regenschirm.',
            'Versuche einen Handstand auf dem Paddelbrett mit Strohhalm in der Nase.',
            'Mach es mit einem Lächeln und einer Prise Glitzer.',
            'Trag einen Superheldenumhang und sing etwas Überraschendes.',
            'Denk an unsichtbare Gummihühner dabei.',
            'Versuch einen Tango mit deinem Schatten.',
            'Auf jeden Fall! Und vergiss die Glitzerkonfetti nicht!',
            'Besser nicht, es könnte zu einer Konfettinami führen.',
            'Natürlich, und dabei immer ein strahlendes Lächeln tragen!',
            'Lass es lieber, das könnte die Gravitationskonstante herausfordern.',
            'Definitiv! Und sing dabei eine epische Hymne für Gummienten.',
            'Hmm, vielleicht nicht, die Raumzeit könnte aus dem Gleichgewicht geraten.',
            'Ja, und bring eine Tasse Tee für deine Zimmerpflanzen mit.',
            'Statt dessen könntest du Stand-up-Comedy mit Zahnseide versuchen.',
            'Tanze auf dem Regenbogen und sing dabei eine mitreißende Ode an deine Socken.',
            'Hmm, vielleicht nicht, das Gedicht des Mondes könnte davon überrascht sein.',
            'Warum nicht? Sei ein Entdecker deiner eigenen skurrilen Wege!',
            'Setz den Schokoladenhelm auf und sing eine bezaubernde Ballade über den Mond.',
            'Sing eine Ballade und tanz dazu im Regen. Gönn dir!',
            'Verhandle nicht mit Ameisen. Die könnten dich zu ihrer Königin ernennen.',
            'Spring auf dem Trampolin mit einem Regenschirm aus Marshmallows.',
            'Versuch einen Handstand auf dem Paddelbrett, natürlich mit einem Strohhalm in der Nase.',
            'Mach es mit einem breiten Lächeln und einer Prise Glitzer. Immer!',
            'Trag einen Superheldenumhang und sing etwas Überraschendes, vielleicht Vogelgezwitscher.',
            'Denk an unsichtbare Gummihühner und vielleicht lächeln sie zurück.',
            'Versuch einen Tango mit deinem Schatten, aber sei bereit für Überraschungen.',
            'Definitiv! Und vielleicht noch eine Prise Glitzer dazu.',
            'Hmm, besser nicht. Konfetti im Haus putzen kann nervig sein.',
            'Natürlich! Immer mit einem strahlenden Lächeln.',
            'Lass es lieber, das könnte die Schwerkraft herausfordern.',
            'Absolut! Sing dabei eine Hymne für Gummienten.',
            'Vielleicht nicht, das Universum könnte verwirrt werden.',
            'Ja, und bring Tee für die Zimmerpflanzen mit, sie verdienen es.',
            'Statt dessen könntest du versuchen, Zahnseide als Mikrofon zu verwenden.',
            'Tanze auf dem Regenbogen und sing dabei eine Ode an deine Socken.',
            'Hmm, vielleicht nicht. Das Gedicht des Mondes mag seine Ruhe.',
            'Warum nicht? Sei ein Abenteurer in deiner eigenen skurrilen Welt!',
            'Setz den Schokoladenhelm auf und sing eine Ballade für den Mond.',
            'Sing eine Ballade und tanz im Regen. Das Leben ist zu kurz für Trockenheit.',
            'Verhandle nicht mit Ameisen. Du wirst am Ende wahrscheinlich verlieren.',
            'Spring auf dem Trampolin mit einem Marshmallow-Regenschirm. Spaß garantiert!',
            'Versuch einen Handstand auf dem Paddelbrett, aber Achtung vor den Enten.',
            'Mach es mit einem Lächeln und einer extra Portion Glitzer.',
            'Trag einen Superheldenumhang und sing etwas Überraschendes, vielleicht Vogelgezwitscher.',
            'Denk an unsichtbare Gummihühner, sie könnten unsichtbare Eier legen.',
            'Versuch einen Tango mit deinem Schatten, sei bereit für ein Schatten-Duett.',
            'Natürlich! Und vergiss nicht, dabei Konfetti zu werfen!',
            'Hmm, besser nicht. Konfetti kann eine hartnäckige Sache sein.',
            'Klar doch! Und denk daran, dabei immer zu lachen.',
            'Vielleicht nicht, das könnte die Schwerkraft herausfordern.',
            'Ja, auf jeden Fall! Sing dabei eine Rockhymne für Gummienten.',
            'Hmm, vielleicht nicht. Das Universum mag seine Geheimnisse.',
            'Ja, und bring eine Tasse Tee für deine Zimmerpflanzen mit.',
            'Warum nicht mal etwas Neues versuchen? Wie wäre es mit einem Comedy-Auftritt mit Zahnseide?',
            'Tanze auf dem Regenbogen und sing dabei eine Liebesballade an deine Socken.',
            'Hmm, vielleicht nicht. Das Gedicht des Mondes könnte sich gestört fühlen.',
            'Natürlich! Sei ein Abenteurer in deiner eigenen, skurrilen Welt!',
            'Setz den Schokoladenhelm auf und sing eine Ballade für den Mond.',
            'Sing eine Ballade und tanz im Regen. Das Leben ist zu kurz für Trockenheit.',
            'Verhandle nicht mit Ameisen. Du wirst wahrscheinlich verlieren.',
            'Spring auf dem Trampolin mit einem Marshmallow-Regenschirm. Spaß pur!',
            'Versuch einen Handstand auf dem Paddelbrett, aber pass auf die Enten auf!',
            'Mach es mit einem Lächeln und einer extra Portion Glitzer.',
            'Trag einen Superheldenumhang und sing etwas Überraschendes, vielleicht Vogelgezwitscher.',
            'Denk an unsichtbare Gummihühner. Sie könnten unsichtbare Eier legen.',
            'Versuch einen Tango mit deinem Schatten. Vielleicht gibt es eine Schatten-Überraschung.',
            'Definitiv! Und dabei eine Glitzerkanone abfeuern.',
            'Besser nicht. Konfetti kann für lange Zeit aufräumen bedeuten.',
            'Natürlich! Immer mit einem Lächeln und einem Augenzwinkern.',
            'Lass es lieber, das könnte die Raumzeit durcheinander bringen.',
            'Ja, auf jeden Fall! Sing dabei eine Ode an die Gummienten.',
            'Hmm, vielleicht nicht. Das Universum könnte dich auslachen.',
            'Ja, und servier Tee für die Zimmerpflanzen. Sie haben es verdient.',
            'Versuch eine Stand-up-Comedy mit Zahnseide. Das Publikum wird es lieben.',
            'Tanze auf dem Regenbogen und sing dabei eine Rockhymne für deine Socken.',
            'Hmm, vielleicht nicht. Das Gedicht des Mondes hat gerade Siesta.',
            'Warum nicht? Sei ein Abenteurer im Dschungel deiner Fantasie!',
            'Setz den Schokoladenhelm auf und sing eine Ballade für den Kosmos.',
            'Sing eine Ballade und tanz im Regen. Das Wasser wird dich nicht beißen.',
            'Verhandle nicht mit Ameisen. Sie sind harte Verhandlungspartner.',
            'Spring auf dem Trampolin mit einem Regenschirm aus Marshmallows. Ein Fest für die Sinne!',
            'Versuch einen Handstand auf dem Paddelbrett. Die Fische werden es lieben.',
            'Mach es mit einem Lächeln und einem Funkeln in den Augen.',
            'Trag einen Superheldenumhang und sing etwas Überraschendes, vielleicht Walgesang.',
            'Denk an unsichtbare Gummihühner. Vielleicht legen sie unsichtbare Goldene Eier.',
            'Versuch einen Tango mit deinem Schatten. Sei darauf vorbereitet, dass er zurücktanzt.',
            'Klar doch! Und währenddessen Glitzer in die Luft werfen.',
            'Besser nicht. Konfetti kann sich überall verstecken.',
            'Auf jeden Fall! Mit einem breiten Lächeln im Gesicht.',
            'Lass es lieber, das könnte die Dimension der Realität verzerren.',
            'Ja, warum nicht! Sing dabei eine Hymne für alle Enten.',
            'Hmm, vielleicht nicht. Das Universum könnte gerade beschäftigt sein.',
            'Ja, und servier Tee für die Zimmerpflanzen. Sie mögen Abwechslung.',
            'Probier Stand-up-Comedy mit Zahnseide. Vielleicht wird sie deine Witze verstehen.',
            'Tanze auf dem Regenbogen und sing dabei eine Huldigung an deine Socken.',
            'Hmm, vielleicht nicht. Das Gedicht des Mondes ist heute nicht in Stimmung.',
            'Natürlich! Sei ein Forscher in deiner eigenen verrückten Welt!',
            'Setz den Schokoladenhelm auf und sing eine Ballade für die Sterne.',
            'Sing eine Ballade und tanz im Regen. Die Wolken applaudieren dir.',
            'Verhandle nicht mit Ameisen. Sie könnten nach Gehaltserhöhung fragen.',
            'Spring auf dem Trampolin mit einem Marshmallow-Regenschirm. Ein Fest für die Geschmacksknospen!',
            'Versuch einen Handstand auf dem Paddelbrett. Halte Ausschau nach neidischen Fischen.',
            'Mach es mit einem Lächeln und einer extra Portion Glitzerzauber.',
            'Trag einen Superheldenumhang und sing etwas Überraschendes, vielleicht eine Hymne für Glühbirnen.',
            'Denk an unsichtbare Gummihühner. Sie könnten unsichtbare Nester bauen.',
            'Versuch einen Tango mit deinem Schatten. Er wird es dir danken.',
            'Klar doch! Und währenddessen Konfetti in den Himmel schicken.',
            'Besser nicht. Konfetti kann zu unerwarteten Orten fliegen.',
            'Natürlich! Immer mit einem Lächeln und einer Prise Magie.',
            'Lass es lieber, das könnte die Matrix durcheinanderbringen.',
            'Ja, warum nicht! Und dabei eine Hymne für alle Gänse singen.',
            'Hmm, vielleicht nicht. Das Universum könnte gerade ein Nickerchen machen.',
        ]
        let antwortenWithoutQuestion = [
            'Zähl die Fliesen im Badezimmer, um deinen Geist zu schärfen.',
            'Übe das Jonglieren mit Orangen, um deine Fähigkeiten im Multitasking zu verbessern.',
            'Trage immer eine Banane in der Tasche, für den Fall, dass du auf eine Affenparty eingeladen wirst.',
            'Lass regelmäßig Luftballons in deinem Haus schweben, um deine Zuhause-auf-Wolken-Gefühl zu steigern.',
            'Verwende einen Fallschirm beim Verlassen deines Bettes, um jeden Tag mit einem Abenteuer zu beginnen.',
            'Züchte einen Miniatur-Garten auf deiner Tastatur für eine frische Arbeitsatmosphäre.',
            'Stelle eine Stoppuhr auf, wenn du Wasser kochst, um deine Weltrekordzeit zu verbessern.',
            'Trage immer Socken auf den Händen, um warme "Handschuhe" zu haben.',
            'Nutze eine Krawatte als Gürtel, um deinem Outfit eine gewisse Klasse zu verleihen.',
            'Trainiere deine Haustiere, um morgens dein Frühstück zu kochen.',
            'Verwende eine Zahnbürste als Mikrofon, um während der Hausarbeit eine private Gesangsshow zu geben.',
            'Iss Gummibärchen, um deine Kiefermuskeln zu stärken.',
            'Dekoriere deine Wände mit leeren Pizzakartons für eine kulinarische Wohnatmosphäre.',
            'Versuche, deinen Schatten zu überlisten, um ein Spiel des Versteckens zu starten.',
            'Schlaf mit einem Buch unter deinem Kissen, um von Wissen durchträumt zu werden.',
            'Trage einen Regenschirm im Haus, um auf alles vorbereitet zu sein.',
            'Vergiss nie, deine Socken zu sortieren, bevor du ausgehst.',
            'Trage immer eine Sonnenbrille, auch nachts.',
            'Zähle die Kieselsteine am Straßenrand, um deine Gedanken zu ordnen.',
            'Lerne, mit Pinguinen zu tanzen, es könnte dir in einer Eiszeit helfen.',
            'Übe das Jonglieren mit Marshmallows, nur für den Fall, dass du in einem Zirkus landest.',
            'Trage immer zwei verschiedene Socken, um deine kreative Seite zu betonen.',
            'Benutze eine Gabel, um deine Haare zu kämmen, für den zusätzlichen Glanz.',
            'Trinke dein Wasser nur in geraden Schlucken, um deine Chakren auszubalancieren.',
            'Trage einen Regenschirm, auch wenn die Sonne scheint, um den Regenbogen zu suchen.',
            'Vermeide es, auf Treppen zu laufen, um die Geister der Vergangenheit nicht zu stören.',
            'Singe "Happy Birthday" rückwärts, um den Tag rückgängig zu machen.',
            'Spreche mit deinen Zimmerpflanzen, um ihr Selbstwertgefühl zu stärken.',
            'Trage eine Wärmflasche in der Hosentasche, um jederzeit warme Gedanken zu haben.',
            'Male deine Zehennägel mit Glitzerstiften, um den inneren Glamour zu betonen.',
            'Trage eine Wollmütze im Sommer, um die Sonne zu ärgern und den Winter zu beschwören.',
            'Lerne, mit einem Einhorn zu reiten, falls du jemals auf einer magischen Mission bist.',
            'Trage Handschuhe beim Essen, um eine tiefe Verbindung zu deinem Besteck herzustellen.',
            'Entfalte deine Socken vor dem Schlafengehen, um ihnen eine gute Nachtruhe zu gönnen.',
            'Habe immer ein Buch über Quantenphysik dabei, um Smalltalk auf eine andere Ebene zu bringen.',
            'Fange an, mit den Vögeln zu flüstern, um ihr Vertrauen zu gewinnen.',
            'Trage immer verschiedene Socken, um einen Modetrend zu setzen.',
            'Stelle sicher, dass deine Zimmerpflanzen jeden Tag ein Gedicht hören, um ihr Wachstum zu fördern.',
            'Verwende Zahnpasta als Gesichtscreme für einen erfrischenden Teint.',
            'Trinke deinen Kaffee durch einen Strohhalm, um ihn stilvoller zu genießen.',
            'Übe das Tanzen mit deinem Staubsauger, um auf jede Party vorbereitet zu sein.',
            'Baue eine Zeitmaschine, um gestern das Mittagessen zu essen und es noch einmal zu genießen.',
            'Schreibe eine Liebeserklärung an deine E-Mails, bevor du sie sendest.',
            'Trage Flip-Flops im Regen, um kostenlose Fußmassagen zu erhalten.',
            'Sammle Glückskekse, um herauszufinden, ob das Glück sich vermehrt, wenn du sie aufisst.',
            'Veranstalte ein Picknick im Wohnzimmer, um die Freiheit des Essens zu erleben, ohne von Ameisen gestört zu werden.',
            'Verkleide dich als Geist, wenn du dein Zimmer betrittst, um die Möbel zu erschrecken.',
            'Trage einen Hut aus Alufolie, um dich vor Gedankenkontrolle zu schützen.',
            'Sprich mit deinem Spiegelbild, um sicherzustellen, dass du immer auf einer Wellenlänge bist.',
            'Male deine Nägel mit unsichtbarem Lack, um einen minimalistischen Look zu kreieren.',
            'Benutze einen Regenschirm im Haus, um vor möglichen Indoor-Regenschauern geschützt zu sein.',
            'Schreibe ein Buch über das Leben deiner Gummiente, um ihre Erfahrungen zu teilen.',
            'Schicke deinen Schatten zum Einkaufen, um sicherzustellen, dass er immer im Trend ist.',
            'Trage deinen Pyjama tagsüber, um dem Leben eine gemütliche Note zu verleihen.',
            'Koche Spaghetti mit der Gabel im Mund, um Zeit bei der Zubereitung zu sparen.',
            'Baue einen Schneemann im Sommer, um die Sonne herauszufordern.',
            'Versuche, eine Unterhaltung mit deinem Kühlschrank zu führen, um deine Kommunikationsfähigkeiten zu verbessern.',
            'Baue ein Kissenfort in deinem Wohnzimmer, um dich vor den Anforderungen des Erwachsenenlebens zu verstecken.',
            'Trage einen Umhang, während du Geschirr spülst, um die "Superheld des Haushalts-Aura" zu verstärken.',
            'Mache ein Foto von deinem Frühstück und schicke es an einen Astronauten, um kosmische Frühstückstipps zu erhalten.',
            'Halte eine Rede für deine Zimmerpflanzen über die Bedeutung von Sonnenlicht und regelmäßigem Gießen.',
            'Veranstalte eine Teeparty für deine Stofftiere, um eine positive soziale Atmosphäre zu fördern.',
            'Schreibe einen Liebesbrief an deine Schuhe, um ihre Treue zu würdigen.',
            'Tanze durch dein Wohnzimmer, während du einen imaginären Tango mit einer unsichtbaren Person führst.',
            'Versuche, einen Tag lang rückwärts zu leben, um die Zeit auf eine alternative Weise zu erleben.',
            'Rufe eine Pizzabestellung auf eine imaginäre Telefonnummer an, um die Pizza der Fantasie zu bestellen.',
            'Erstelle eine Liste von Gründen, warum Marshmallows die perfekten Haustiere wären.',
            'Lege einen Spaziergang auf deinem Teppich zurück, um virtuelle Kilometer zu sammeln.',
            'Baue ein Schneemannfamilie aus Klopapierrollen, um winterliche Stimmung zu verbreiten.',
            'Gib Gas und genieße die Fahrt!',
            'Überleg es dir nochmal bei einer Tasse Tee.',
            'Mach es einfach! YOLO!',
            'Konsultiere eine Glaskugel für die ultimative Antwort.',
            'Hör auf dein Bauchgefühl, es kennt die Antwort.',
            'Mach einen Pro-Contra-Liste und entscheide dann, wie du willst.',
            'Frag einen Freund. Vielleicht haben sie einen brillanten Einfall.',
            'Setz Prioritäten und erledige das Wichtigste zuerst.',
            'Stell dir vor, du würdest es einer Gummiente erklären. Was würde sie sagen?',
            'Hör auf dein Herz, es schlägt im Takt deiner Wünsche.',
            'Folge dem Regenbogen, vielleicht findest du dort deine Antwort.',
            'Mach eine Liste von Vor- und Nachteilen und bewerte sie.',
            'Frag dich, ob du es in fünf Jahren bereuen würdest, es nicht getan zu haben.',
            'Setz klare Ziele und überleg, wie deine Entscheidung sie beeinflussen wird.',
            'Lerne aus der Vergangenheit, aber lebe im Hier und Jetzt.',
            'Mach einen Reality-Check: Wie realistisch ist deine Option?',
            'Meditiere für Klarheit und innere Ruhe.',
            'Frag die Magie-8-Ball, er kennt alle Antworten.',
            'Folge dem Fluss des Lebens und sieh, wohin er dich führt.',
            'Denk daran: Manchmal ist der Weg das Ziel.',
            'Mach eine Abwägung zwischen Risiko und Belohnung.',
            'Frag dich, ob diese Entscheidung zu deinen langfristigen Zielen passt.',
            'Hör auf deine Intuition, sie kennt den Weg.',
            'Frag die Vögel. Ihr Gezwitscher könnte Weisheit enthalten.',
            'Mach eine Blitzumfrage unter Freunden für verschiedene Perspektiven.',
            'Erstell eine Mindmap und visualisiere deine Optionen.',
            'Frag dich, ob diese Entscheidung zu deinen Werten passt.',
            'Denk daran, dass jede Entscheidung eine Erfahrung ist, egal welche du triffst.',
            'Stell dir vor, du würdest es einem Zeitreisenden erklären. Was würde er sagen?',
            'Reflektiere über deine Stärken und Schwächen in Bezug auf die Entscheidung.',
            'Hör auf deinen inneren Zirkuselefanten. Er kennt den Weg durch den Dschungel des Lebens.',
            'Überleg, ob diese Entscheidung dich persönlich wachsen lässt.',
            'Frag dich, ob du in der Zukunft stolz auf diese Entscheidung sein wirst.',
            'Mach eine Prognose, welche Auswirkungen die Entscheidung in einem Jahr haben wird.',
            'Frag dich, ob diese Entscheidung dich glücklicher machen wird.',
            'Hör auf den Rat von Dingen, die dir am Herzen liegen.',
            'Frag dich, ob diese Entscheidung deinen Zielen dient oder sie behindert.',
            'Denk daran, dass es keine falschen Entscheidungen gibt, nur Lernerfahrungen.',
            'Hör auf deine inneren Weisen. Sie sind vielleicht schweigsam, aber klug.',
            'Frag dich, ob diese Entscheidung deinen Werten und Überzeugungen entspricht.',
            'Denk daran, dass jede Entscheidung eine Tür zu neuen Möglichkeiten öffnet.',
            'Frag dich, ob diese Entscheidung einen positiven Beitrag zur Welt leistet.',
            'Hör auf das Rauschen der Bäume im Wind. Sie flüstern manchmal gute Ratschläge.',
            'Frag dich, ob diese Entscheidung einen kleinen Funken Freude entzündet.',
            'Mach einen Rückblick auf deine vergangenen Erfolge und lerne daraus.',
            'Frag dich, ob diese Entscheidung deinen inneren Künstler inspiriert.',
            'Denk daran, dass du die Kapitänin deines Lebensschiffs bist. Steuer klug.',
            'Frag dich, ob diese Entscheidung Harmonie in dein Leben bringt.',
            'Hör auf den Klang der Wellen. Manchmal tragen sie die besten Antworten heran.',
            'Frag dich, ob diese Entscheidung das Licht in dir zum Leuchten bringt.',
            'Überleg, ob diese Entscheidung zu einem positiven Schneeballeffekt führen kann.',
            'Denk daran, dass du nicht alles sofort wissen musst. Manchmal klärt sich alles mit der Zeit.',
            'Frag dich, ob diese Entscheidung einen Hauch von Abenteuer mit sich bringt.',
            'Hör auf das Flüstern der Sterne. Sie kennen möglicherweise die Antwort.',
            'Frag dich, ob diese Entscheidung dein Herz schneller schlagen lässt.',
            'Denk daran, dass du immer die Wahl hast, deine Entscheidungen zu überdenken.',
            'Frag dich, ob diese Entscheidung zu einem Lächeln auf deinem Gesicht führt.',
            'Folge deinem Herzen, es kennt den Weg.',
            'Sei mutig und nimm Herausforderungen an.',
            'Priorisiere Selbstpflege und gönn dir Pausen.',
            'Glaube an dich selbst, du bist stärker als du denkst.',
            'Sei offen für Veränderungen, sie bringen oft Wachstum.',
            'Schätze die kleinen Freuden des Lebens.',
            'Handle mit Freundlichkeit, es kostet nichts.',
            'Setze klare Ziele und arbeite beharrlich darauf hin.',
            'Höre auf deine Intuition, sie irrt selten.',
            'Umgebe dich mit positiven Menschen, die dich inspirieren.',
            'Sei geduldig, gute Dinge brauchen Zeit.',
            'Lerne aus Fehlern und sieh sie als Chancen zum Wachsen.',
            'Pflege deine Beziehungen, sie sind wertvoll.',
            'Gib nicht auf, wenn es schwierig wird. Du schaffst das!',
            'Sei dankbar für das, was du hast.',
            'Erforsche die Welt und lerne kontinuierlich dazu.',
            'Vertraue auf den Prozess des Lebens.',
            'Finde einen Ausgleich zwischen Arbeit und Freizeit.',
            'Sage öfter mal Ja zu neuen Erfahrungen.',
            'Halte inne und genieße den gegenwärtigen Moment.',
            'Habe Respekt vor anderen und ihren Perspektiven.',
            'Investiere Zeit in deine Selbstreflexion.',
            'Handle mit Bedacht, aber zögere nicht, Risiken einzugehen.',
            'Akzeptiere Veränderungen als natürlichen Teil des Lebens.',
            'Sei großzügig, teile dein Glück mit anderen.',
            'Bleibe neugierig und offen für Neues.',
            'Stärke deine mentale Gesundheit durch positive Gedanken.',
            'Feiere deine Erfolge, auch die kleinen.',
            'Suche nach Lösungen, wenn du auf Hindernisse triffst.',
            'Erkenne deine Stärken und arbeite an deinen Schwächen.',
            'Höre aufmerksam zu und zeige Empathie.',
            'Bleibe fokussiert, aber sei flexibel in deinen Plänen.',
            'Setze klare Grenzen und stehe zu deinen Überzeugungen.',
            'Entwickle eine positive Morgenroutine.',
            'Übernehme Verantwortung für dein eigenes Glück.',
            'Sei ein Vorbild für Freundlichkeit und Mitgefühl.',
            'Fördere eine positive Einstellung, sie ist ansteckend.',
            'Finde Freude in den kleinen Details des Alltags.',
            'Halte dich von negativen Einflüssen fern.',
            'Entwickle einen Sinn für Humor, er erleichtert vieles.',
            'Baue ein unterstützendes Netzwerk von Menschen um dich herum auf.',
            'Sei offen für Kritik, sie kann Wachstum fördern.',
            'Lasse dich nicht von Rückschlägen entmutigen.',
            'Erfülle deine Pflichten mit Hingabe und Liebe.',
            'Finde Wege, um Stress abzubauen und zu entspannen.',
            'Sei geduldig mit dir selbst, niemand ist perfekt.',
            'Erforsche deine Leidenschaften und folge ihnen.',
            'Überlege gut, bevor du Entscheidungen triffst, aber traue deinem Instinkt.',
            'Fördere eine Umgebung des Vertrauens und der Offenheit.',
            'Entwickle deine Fähigkeiten und bilde dich kontinuierlich weiter.',
            'Sei ein Brückenbauer, wenn es um Konflikte geht.',
            'Lerne, Nein zu sagen, wenn es notwendig ist.',
            'Pflege deine kreative Seite, sie bereichert dein Leben.',
            'Erforsche verschiedene Perspektiven und erweitere deinen Horizont.',
            'Bleibe authentisch und loyal zu dir selbst.',
            'Erkenne die Schönheit in der Vielfalt.',
            'Erlaube dir, Fehler zu machen, sie sind Teil des Lernens.',
            'Praktiziere Dankbarkeit, auch in schwierigen Zeiten.',
            'Halte an deinen Träumen fest und arbeite auf sie hin.',
            'Umarme Veränderungen als Chancen für Wachstum.',
            'Pflege eine gesunde Balance zwischen Arbeit und Privatleben.',
            'Probier etwas Neues aus und entdecke deine kreative Seite!',
            'Denk positiv und sieh die Herausforderungen als Chancen.',
            'Höre auf dein Bauchgefühl, es irrt selten.',
            'Gib dir selbst die Erlaubnis, auch mal "Nein" zu sagen.',
            'Setz klare Ziele und arbeite beharrlich darauf hin.',
            'Suche nach Lösungen, nicht nach Problemen.',
            'Pflege deine Beziehungen und schätze deine Freunde.',
            'Investiere Zeit in Selbstreflexion und persönliche Entwicklung.',
            'Bleib flexibel und offen für Veränderungen.',
            'Sei freundlich zu dir selbst und akzeptiere deine Fehler.',
            'Vertraue darauf, dass alles mit der Zeit besser wird.',
            'Feiere deine Erfolge, egal wie klein sie sind.',
            'Setz Prioritäten und konzentriere dich auf das Wesentliche.',
            'Lerne aus der Vergangenheit, aber lebe im Hier und Jetzt.',
            'Höre auf deinen Körper und sorge gut für deine Gesundheit.',
            'Kommuniziere klar und respektvoll.',
            'Suche nach Möglichkeiten, anderen zu helfen und Gutes zu tun.',
            'Sei neugierig und bleibe stets lernbereit.',
            'Vermeide Drama und konzentriere dich auf positive Energie.',
            'Entwickle eine Routine für mehr Struktur im Alltag.',
            'Lass los, was du nicht ändern kannst, und konzentriere dich auf das, was du beeinflussen kannst.',
            'Verfolge deine Leidenschaften und finde Freude in dem, was du tust.',
            'Folge deinen Träumen, auch wenn sie unkonventionell erscheinen.',
            'Lächle öfter, es macht nicht nur dich, sondern auch andere glücklich.',
            'Bleib geduldig, gute Dinge brauchen Zeit.',
            'Sei offen für neue Perspektiven und Denkweisen.',
            'Bleib authentisch und steh zu deinen Überzeugungen.',
            'Umgebe dich mit positiven Menschen, die dich unterstützen.',
            'Höre auf deine Intuition, sie ist oft weiser als du denkst.',
            'Fokussiere dich auf Lösungen, nicht auf Probleme.',
            'Pflege deine kreativen Ausdrucksformen, egal welcher Art.',
            'Investiere Zeit in Selbstpflege und achte auf deine Bedürfnisse.',
            'Bleib optimistisch, auch in schwierigen Zeiten.',
            'Akzeptiere Veränderungen als Teil des Lebens und wachse daran.',
            'Zeige Dankbarkeit für die kleinen Dinge im Leben.',
            'Sei großzügig mit deiner Zeit, deinem Wissen und deiner Liebe.',
            'Entwickle eine gesunde Work-Life-Balance.',
            'Fokussiere dich auf Lösungen anstatt auf Probleme.',
            'Glaube an deine Fähigkeiten und stärke dein Selbstvertrauen.',
            'Erforsche regelmäßig neue Ideen und Horizonte.',
            'Ermuntere andere und teile positive Energien.',
            'Bleib neugierig und lass die Freude am Lernen nie nach.',
            'Setz klare Grenzen und respektiere die Grenzen anderer.',
            'Akzeptiere, dass Perfektion nicht realistisch ist.',
            'Setze realistische Ziele und arbeite schrittweise darauf hin.',
            'Praktiziere Achtsamkeit und lebe im gegenwärtigen Moment.',
            'Schätze die kleinen Freuden im Alltag.',
            'Nimm Herausforderungen als Gelegenheiten zur persönlichen Entwicklung an.',
            'Umgebe dich mit positiven Menschen, die dich inspirieren.',
            'Pflege deine geistige und emotionale Gesundheit.',
            'Lerne aus Fehlern und betrachte sie als Chancen zu wachsen.',
            'Gib dir selbst die Erlaubnis, Grenzen zu setzen und "Nein" zu sagen.',
            'Suche nach Schönheit und Positivität in deiner Umgebung.',
            'Erkenne deine Stärken an und arbeite daran, sie weiter zu entwickeln.',
            'Nimm dir Zeit für Selbstreflexion und persönliches Wachstum.',
            'Bleib in herausfordernden Momenten geduldig und behalte einen klaren Kopf.',
            'Entwickle eine positive Denkweise und erkenne den Wert von Optimismus.',
            'Setz dir Ziele, die dich motivieren und inspirieren.',
            'Fördere ein Gefühl der Dankbarkeit für das, was du hast.',
            'Stärke deine Resilienz und finde Wege, Krisen zu überwinden.',
            'Ermutige andere, ihr Bestes zu geben und ihre Ziele zu verfolgen.',
            'Pflege deine sozialen Beziehungen und investiere Zeit in deine Liebsten.',
            'Sei achtsam gegenüber deiner Umwelt und der Natur.',
            'Ermuntere Kreativität und Innovation, sei offen für neue Ideen.',
            'Fokussiere dich auf Lösungen und suche nach positiven Auswegen.',
            'Akzeptiere Veränderungen als natürlichen Teil des Lebens.',
            'Nimm dir Zeit für Selbstpflege, um deine Energie aufzuladen.',
            'Schätze die Vielfalt und lerne von unterschiedlichen Perspektiven.',
            'Tauche in ein Walfisch-Lagerhaus voller Kaugummis ein!',
            'Lerne Pinguin-Charme, um in jeder Situation zu glänzen.',
            'Trage einen Helm aus Wassermelone, um Gedankenübertragung zu verhindern.',
            'Schreibe Liebesbriefe an deine E-Mails. Liebe braucht schließlich keinen Grund.',
            'Gib Glückskeksen eine Chance, dein Leben zu revolutionieren.',
            'Schicke deinen Schatten auf einen Kaffee, um eine Schattenfreundschaft zu beginnen.',
            'Veranstalte ein Picknick im Wohnzimmer, um die Freiheit des Essens zu erleben.',
            'Übe das Jonglieren mit unsichtbaren Früchten für den nächsten Karneval.',
            'Sammle Gummibärchen, um ein Gummibärchenimperium zu gründen.',
            'Trage Flip-Flops im Regen, um kostenlose Fußmassagen zu erhalten.',
            'Verkleide dich als Geist, wenn du dein Zimmer betrittst, um die Möbel zu erschrecken.',
            'Sprich mit deinem Spiegelbild, um sicherzustellen, dass du immer auf einer Wellenlänge bist.',
            'Male deine Nägel mit unsichtbarem Lack, um einen minimalistischen Look zu kreieren.',
            'Benutze einen Regenschirm im Haus, um vor möglichen Indoor-Regenschauern geschützt zu sein.',
            'Schreibe ein Buch über das Leben deiner Gummiente, um ihre Erfahrungen zu teilen.',
            'Schicke deinen Schatten zum Einkaufen, um sicherzustellen, dass er immer im Trend ist.',
            'Trage deinen Pyjama tagsüber, um dem Leben eine gemütliche Note zu verleihen.',
            'Koche Spaghetti mit der Gabel im Mund, um Zeit bei der Zubereitung zu sparen.',
            'Baue einen Schneemann im Sommer, um die Sonne herauszufordern.',
            'Schwimme gegen den Strom, es sei denn, der Strom ist aus Schokolade.',
            'Trainiere Ameisen als persönliche Bodyguards, du weißt nie, wann sie nützlich sein könnten.',
            'Erfinde eine geheime Handshake-Sprache mit deinem Schatten, um ihn besser zu verstehen.',
            'Organisiere ein Luftgitarrenkonzert im Wohnzimmer, um die Nachbarn zu beeindrucken.',
            'Verwandle deine Kühlschranktür in eine Kunstgalerie für magnetische Gedanken.',
            'Lerne die Kunst des rückwärts Wasserkocherfüllens für einen Hauch von Magie.',
            'Führe einen monologischen Dialog mit deiner Zahnbürste, um sie zu motivieren.',
            'Trainiere deine Haustiere als Geheimagenten, damit sie die Nachbarschaft im Auge behalten.',
            'Erkläre deinem Staubsauger, dass er nicht nur ein Gerät, sondern ein Held ist.',
            'Überrede eine Pflanze, deine Autobiographie zu schreiben, um die Welt zu überraschen.',
            'Veranstalte einen Kopfstandwettbewerb mit deinem Spiegelbild, um die Perspektive zu ändern.',
            'Baue eine Zeitmaschine, um gestern das Mittagessen zu essen und es noch einmal zu genießen.',
            'Verwandle das Wohnzimmer in einen Dschungel und führe Gespräche mit den Kissenaffen.',
            'Rede mit den Blumen, aber sei gewarnt: manchmal flüstern sie zurück.',
            'Kaufe ein Kostüm für deine Kaffeetasse und veranstalte eine Mini-Fashion-Show.',
            'Stelle fest, ob Gummibärchen hüpfen, wenn niemand hinsieht. Spoiler: Sie tun es.',
            'Fordere deine Schatten zu einem Tanzduell heraus und sieh, wer gewinnt.',
            'Entwickle eine Sprache, die nur du und deine Zehen verstehen, um geheime Pläne zu schmieden.',
            'Trage eine Sonnenbrille, wenn du mit deinem Computer sprichst, um den Coolness-Faktor zu erhöhen.',
            'Überzeuge deine Socken, dass sie eine Rockband gründen sollten. Sock \'n\' Roll!',
            'Trainiere deinen Staubsauger, um Breakdance zu machen, wenn das Haus besonders sauber ist.',
            'Lege einen geheimen Tunnel zwischen deinem Sofa und dem Kühlschrank an, für schnellen Zugang zu Snacks.',
            'Halte eine imaginäre Teeparty für deine Teddybären ab und frage sie nach Lebensratschlägen.',
            'Lehre deine Schatten, wie man Schattentheater spielt, um gemeinsam Geschichten zu erfinden.',
            'Baue eine Geheimsprache mit deinen Pflanzen auf, um über die neuesten Gartenklatsch zu plaudern.',
            'Schmücke dein Zimmer mit unsichtbaren Kunstdrucken, um eine unsichtbare Galerie zu gründen.',
            'Tanze mit dem Staubwedel, während du die Möbel putzt, um den Reinigungstanz zu perfektionieren.',
            'Veranstalte eine Luftgitarren-Meisterschaft im Badezimmer und kröne dich selbst zum Luftgitarren-Champion.',
            'Überlege, wie man eine Pizza in Kreisen schneidet, um das wahre Geheimnis des Universums zu enthüllen.',
            'Bringe deinem Haustier bei, Witze zu erzählen, um die beste Comedy-Show im Haus zu haben.',
            'Organisiere ein Wettrennen mit Schnecken, um zu sehen, wer die Langsamkeit beherrscht.',
            'Rufe beim Einkaufen \'Bingo!\' wenn du alle Artikel auf deiner Liste gefunden hast.',
            'Entwickle einen Händedruck mit deiner Kaffeetasse, um morgendliche Energie zu teilen.',
            'Erstelle ein Tagebuch für deine Träume und gib ihnen eine Bewertung wie bei einem Kinofilm.',
            'Gib deinem Staubsauger einen Spitznamen und erkläre ihm, dass er der MVP des Hauses ist.',
            'Starte einen imaginären Buchclub mit deinen Büchern und diskutiere ihre \'Charakterentwicklung\'.',
            'Veranstalte eine Unterwasser-Party in der Badewanne, komplett mit Gummitier-Gästen.',
            'Lehre deinen Wecker den Moonwalk, damit das Aufwachen zu einer tänzerischen Erfahrung wird.',
            'Erkläre deiner Fernbedienung, dass sie der Schlüssel zur Kontrolle des Universums ist.',
            'Führe ein Interview mit deinem Schatten und finde heraus, welche dunklen Geheimnisse er hat.',
            'Halte eine Modenschau für deine Kleiderschrankinhalt ab und küre den stilvollsten Pullover.',
            'Überrede deine Zimmerpflanzen, dass sie deine persönlichen Yoga-Instruktoren sind.',
            'Organisiere einen Wettkampf zwischen deinen Socken, um den Titel des schnellsten Sockenpaares.',
            'Gib jedem deiner Haushaltsgeräte einen Namen und frage sie täglich, wie es ihnen geht.',
            'Baue ein Labyrinth aus Kissen auf dem Boden und finde heraus, ob du den Ausgang ohne Hilfe findest.',
            'Lehre deinen Schatten das Fliegen, damit er dich begleiten kann, wenn du abhebst.',
            'Veranstalte einen Märchenabend für deine Schuhe und erzähle ihnen, wie sie zu deinen Füßen kamen.',
            'Lege eine \'Tanzverbot\'-Stunde für deine Möbel fest und beobachte, wer sich daran hält.',
            'Trainiere eine Ameise als persönlichen Fitnesstrainer für atemberaubende Mini-Workouts.',
            'Erkläre deinem Spiegelbild, dass es der Grund für deinen großartigen Tag ist.',
            'Führe ein Kaffeekränzchen für deine Kaffeetassen durch und diskutiere die neuesten Kaffeetrends.',
            'Baue eine Zeitmaschine aus Kissen und reise in die Vergangenheit der gemütlichen Nächte.',
            'Veranstalte ein Ping-Pong-Turnier zwischen deinen Händen, um die Hand-Auge-Koordination zu verbessern.',
            'Halte eine Parade für Gummibärchen und kröne das majestätischste Gummibärchen zum König.',
            'Übe das Zähneputzen im Spiegel und überzeuge ihn davon, dass er auch eine Zahnbürste braucht.',
            'Starte einen Podcast mit deinem Wasserkocher und erfahre mehr über seine aufregende Welt.',
            'Organisiere eine \'Stille-Stunde\' für deine Socken, damit sie sich ausruhen können.',
            'Veranstalte eine Konferenz mit deinen Haushaltsgegenständen und bespreche die aktuellen \'Hausangelegenheiten\'.',
            'Lehre deine Schatten das Versteckspiel und sei gespannt, wer gewinnt.',
            'Erkläre deinem Toaster, dass er ein echter \'Aufheizer\' ist und viel Wärme in dein Leben bringt.',
            'Führe eine wissenschaftliche Studie darüber durch, wie viele Kissen auf dem Bett maximalen Komfort bieten.',
            'Veranstalte eine Modenschau für deine Küchengeräte und küre den schicksten Mixer.',
            'Überrede deine Haustiere dazu, sich in deiner Abwesenheit als Superhelden zu verkleiden.',
            'Baue eine Kartenburg und halte eine \'Burgenturnier\' mit deinen Handys ab.',
            'Organisiere eine \'Stift-Rallye\' und finde heraus, welcher Stift der schnellste ist.',
            'Lehre deine Uhr, wie man rückwärts zählt, um die Zeit rückwärts zu erleben.'
        ]

        if (frage) {
            for (let i = antwortenQuestion.length - 1; i > 0; i--) {
                const j = Math.floor(Math.random() * (i + 1));
                const temp = antwortenQuestion[i];
                antwortenQuestion[i] = antwortenQuestion[j];
                antwortenQuestion[j] = temp;
            }

            let randomNumber = Math.floor(Math.random() * antwortenQuestion.length);

            let krassesEmbed = new Discord.MessageEmbed()
                .setColor('#636363')
                .addFields(
                    { name: 'Frage', value: frage },
                    { name: 'Antwort', value: antwortenQuestion[randomNumber] }
                )
                .setTitle('Advice')
                .setFooter('Frage von ' + interaction.user.username, interaction.user.displayAvatarURL)

            await interaction.editReply({ embeds: [krassesEmbed] });

        } else {
            for (let i = antwortenWithoutQuestion.length - 1; i > 0; i--) {
                const j = Math.floor(Math.random() * (i + 1));
                const temp = antwortenWithoutQuestion[i];
                antwortenWithoutQuestion[i] = antwortenWithoutQuestion[j];
                antwortenWithoutQuestion[j] = temp;
            }

            let randomNumber = Math.floor(Math.random() * antwortenWithoutQuestion.length);

            let krassesEmbed = new Discord.MessageEmbed()
                .setColor('#636363')
                .addFields(
                    { name: 'Ratschlag', value: antwortenWithoutQuestion[randomNumber] }
                )
                .setTitle('Advice')
                .setFooter('Benötigt von ' + interaction.user.username, interaction.user.displayAvatarURL)

            await interaction.editReply({ embeds: [krassesEmbed] });
        }
    },
};